### ISSUE TITLE
maximum amount of text data you tested this code with?

### ISSUE THREAD

**Issue by wowcut** [rap2hpoutre/similar-text-finder#8]
Hi, I would like to better understand for which scale did you write this code?
What is the maximum amount of text you did test this code with?
Did you use some known text collections to check he performance?
How doe it compare to established libs like e.g. [gensim](https://radimrehurek.com/gensim/)?
Thanks!

**Comment by rap2hpoutre** [comment]
Hi and thank you for your contribution.

> Hi, I would like to better understand for which scale did you write this code?

Story time: I created this lib years ago because we (my company) needed to suggest a french department (there is about ~100 departments) when users type words with typo. Selecting a department was a mandatory step and the UX team thought it would be better to let them type something rather than displaying a list. And I open sourced this lib because I thought it could help (since I did not found anything in PHP at this time for this need). But I never used it for something else, so I HAVE ABSOLUTLY NO IDEA about scaling. I did not do benchmarks. Still, it seems it's used by some other projects (~500 dl a month, woohoo!), so I continue to maintain it and I am happy with this situation.

> What is the maximum amount of text you did test this code with?

The list of 100 french department (so almost nothing).

> Did you use some known text collections to check he performance?

No.

> How doe it compare to established libs like e.g. gensim?

Mine is a toy :).

Thanks for your question!
